version: '3.5'

services:
  website:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: apache
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80