name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
  
  upload-website:
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: sftp://${{ secrets.HOSTING_URL }}/subdomains/dev/
        ftp-username: ${{ secrets.HOSTING_USERNAME }}
        ftp-password: ${{ secrets.HOSTING_PASSWORD }}
        git-ftp-args: --insecure --silent
