name: vvdespuyt

on:
  push:
    branches: [ master ]

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: bash getComposer.sh
  
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: sftp://${{ secrets.HOSTING_URL }}/subdomains/dev/
        ftp-username: ${{ secrets.HOSTING_USERNAME }}
        ftp-password: ${{ secrets.HOSTING_PASSWORD }}
        git-ftp-args: --insecure --silent -a
